site_name: Go.Beget.API
repo_url: https://github.com/ThCompiler/go.beget.api.git
repo_name: ThCompiler/go.beget.api
copyright: Copyright &copy; 2024 TheCompiler
nav:
  - Главная: index.md
  - Установка: install.md
  - Функции API:
      - Основное: api/info.md
      - Управление аккаунтом: api/account.md
      - Управление бэкапами: api/backup.md
      - Управление Cron: api/cron.md
      - Управление DNS: api/dns.md
      - Управление FTP: api/ftp.md
      - Управление MySQL: api/mysql.md
      - Управление сайтами: api/site.md
      - Управление доменами: api/domain.md
      - Управление почтой: api/mail.md
      - Сбор статистики: api/stat.md
  - Пример: example.md
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.code.select
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.indexes
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github-alt

  favicon: icon/logo.png
  logo: icon/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ThCompiler/go.beget.api.git
      name: github repository
  alternate:
#    - name: English
#      link: /en/
#      lang: en
    - name: Russian
      link: /ru/
      lang: ru
  version:
    provider: mike
plugins:
  - projects:
      projects_dir: docs